[package]
name = "bosunctl"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
anyhow.workspace = true
bosun-hid = { version = "=0.1.0", path = "../../crates/bosun-hid" }
clap.workspace = true
tracing-subscriber.workspace = true
